@echo off
echo Installing Arabic fonts for Mobile Shop Management System...
echo تثبيت الخطوط العربية لنظام إدارة محل الموبايلات...

python setup_fonts.py

echo.
echo Done! Press any key to exit...
echo تم الانتهاء! اضغط أي زر للخروج...
pause
