[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "customtkinter>=5.2.2",
    "matplotlib>=3.10.5",
    "openpyxl>=3.1.5",
    "pillow>=11.3.0",
]
